#!/bin/bash
# Pre-work
sudo apt update

# install neovim aux tools
sudo apt install -y ripgrep fd-find silversearcher-ag
       
# setup symbolic links to dotfiles
mkdir -p ${ZDOTDIR:-$HOME}/.config/nvim

ln -s -f ${PWD}/nvim/init.lua ${ZDOTDIR:-$HOME}/.config/nvim/init.lua
ln -s -f ${PWD}/nvim/lua ${ZDOTDIR:-$HOME}/.config/nvim/lua
ln -s -f ${PWD}/nvim/spell ${ZDOTDIR:-$HOME}/.config/nvim/spell

# Function to install neovim using brew
install_with_brew() {
    echo "Installing Neovim with brew..."
    brew install neovim
}

# Function to install neovim using apt-get
install_from_src() {
    sudo apt install -y gcc make cmake
    mkdir -p /tmp/nvim_src
    git clone https://github.com/neovim/neovim.git /tmp/nvim_src
    cd /tmp/nvim_src
    make CMAKE_BUILD_TYPE=Release
    sudo make install
    cd ~
    rm -rf /tmp/nvim_src
}

# Ensure nvim is installed
if ! command -v nvim &> /dev/null; then
    if command -v brew &> /dev/null; then
        install_with_brew
    else
        install_from_src
    fi
fi
