#!/bin/bash
# Pre-work
sudo apt update

# install neovim aux tools
sudo apt install -y fd-find silversearcher-ag

# install packer.nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
       
# setup symbolic links to dotfiles
mkdir -p ${ZDOTDIR:-$HOME}/.config
mkdir -p ${ZDOTDIR:-$HOME}/.config/nvim

ln -s -f ${PWD}/nvim/init.lua ${ZDOTDIR:-$HOME}/.config/nvim/init.lua
ln -s -f ${PWD}/nvim/lua ${ZDOTDIR:-$HOME}/.config/nvim/lua
ln -s -f ${PWD}/nvim/spell ${ZDOTDIR:-$HOME}/.config/nvim/spell

# install neovim from source
sudo apt install -y gcc make cmake
mkdir -p /tmp/nvim_src
git clone https://github.com/neovim/neovim.git /tmp/nvim_src
cd /tmp/nvim_src
make CMAKE_BUILD_TYPE=Release
sudo make install

