# Custom aliases
alias vim=nvim
alias :q=exit
alias lg=lazygit

alias gcm="git commit -m"
alias gca="git add -A && git commit -m"
alias gpu="git push -u origin HEAD"
alias gpf="git push --force-with-lease"
alias gp="git push"
alias ga="git add"
alias gaa="git add -A"
alias gs="git status"
alias gsh="git stash -u"
alias gco="git checkout"

if [[ -n "$KITTY_WINDOW_ID" ]]; then
    alias s="kitty +kitten ssh"

  # Set terminal theme based on system theme
  if [[ ( $(getSystemTheme) == *'Dark'* ) ]]; then
    kitty @ --password="cavity-guiding-stereo-volley" kitten themes --reload-in=parent Catppuccin-Mocha
  else
    kitty @ --password="cavity-guiding-stereo-volley" kitten themes --reload-in=parent Catppuccin-Latte
  fi
fi

# Set editor to nvim
export VISUAL=nvim
export EDITOR="$VISUAL"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_DEFAULT_COMMAND='ag --ignore node_modules -g ""' 

. $HOME/.nix-profile/etc/profile.d/nix.sh

#### WORK
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.work" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.work"
fi
