#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Add go to path
path+=('/usr/local/go/bin')
path+=('~/.local/bin')

# Use fd for default fzf command
alias fd=fdfind
export FZF_DEFAULT_COMMAND='fdfind --type f'

alias vim=nvim
alias :q=exit

# Custom functions
mkcd () {
	mkdir -p -- "$1" &&
		cd -P -- "$1"
}

# Source nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

